name: CI / CD
on:
  - push
  - workflow_dispatch
jobs:
  check:
    name: Compile and Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Build TypeScript files
        run: yarn build
      - name: Compile
        run: ./bin/station compile
      - name: Check
        run: ./bin/station check
  publish_stage:
    name: Publish to Staging
    runs-on: ubuntu-latest
    needs: check
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    env:
      SUPERFACE_API_URL: https://superface.dev
      SUPERFACE_STORE_REFRESH_TOKEN: ${{ secrets.STAGING_SUPERFACE_STORE_REFRESH_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Build TypeScript files
        run: yarn build
      - name: Publish
        run: ./bin/station publish --all
  publish_production:
    name: Publish to Production
    runs-on: ubuntu-latest
    needs: check
    if: ${{ github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main' }}
    env:
      SUPERFACE_API_URL: https://superface.ai
      SUPERFACE_STORE_REFRESH_TOKEN: ${{ secrets.PRODUCTION_SUPERFACE_STORE_REFRESH_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Build TypeScript files
        run: yarn build
      - name: Publish
        run: ./bin/station publish --all --force
